travis:
  secure:
    BINSTAR_TOKEN: ssLAUCaLR24o4hDld/1xmPW14f708oc4s7eMMe0rbGhTOPO8d8noHVhNSNEcqyWFo41UqQjkqlfujNuxhb15tG81vSgSGo6cIaxXV92v55gP/0dF33NkNZQE2pXPquKRkeDL7tjUpP4wQSGshm5eKlkFKyXaLM6OTq9p8VBHsWEshmyrGH+rEfwecHWdMUVppzOSzPSPRkavsTRni/lzxJJCyt9aWrTdGNPjNjeTe6rmfZsSpKjQy0vnV4chHyWeX2VTA7EM5keAdGmpLg09G68J+CIsxzDy4RB4YBniA1RVoWWivATre+TbZ+wALcnMFNbTdKwmyJ30tqlsKCBbKi2SgTErSaWiu5bB6X9YQd+Pm+//i3eW2nZ9i1cF7gtN2tUPAs1uoVTbMcOA4pzdqk5jD5Ay06s7EcRWih6fuB2GdQhEJ/O4wYQwRDfxOp3zyoXqOZf9mxVb3nwswwwg/FNrpfes6RoQg469gET5L3Sce2jVsfYJTkjA2ER8c1RlP7vRY+XJcl0FSmYcMl47lW5OQJPxgCWT8Ui+wzxnqNsjA9xmgk2iasuFOXRDeHj9OZJc/JOJNwMUiYTGhrPgcCbqrDVkHGEdfCOQo3NujChTGdIVW413oUHYnBCRRStmMn+b3rVMETB3a0ID4wlAt3dSDma+VeY01UhWjt+T+T8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
